### ISSUE TITLE
Error install  RTSP2WebRTC

### ISSUE THREAD

**Issue by eug314** [AlexxIT/hassio-addons#10]
Failed to install addon
The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2

**Comment by kernelorg** [comment]
Same problem. 
RPi4 + HA 2021.2.3 supervised

**Comment by aleksandryants** [comment]
Same issue

**Comment by exotsk** [comment]
synology?

**Comment by aleksandryants** [comment]
RPi4 + HA 2021.2.3 supervised

**Comment by ironirc** [comment]
On a pi 4:
Failed to install add-on
'NoneType' object has no attribute 'is_file'

**Comment by sanyadez** [comment]
The same thing. Rpi 4b, armbian, ha supervised. Logs:

21-03-05 20:27:44 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build a889bffc/armv7-addon-rtsp2webrtc:0.1.4: The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2
21-03-05 20:27:44 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM
Step 2/15 : FROM $BUILD_FROM
 ---> 21461176cb52
Step 3/15 : RUN apk add --no-cache unzip go jq
 ---> Running in 0f3e982fcf5a
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  go (no such package):
    required by: world[go]
  unzip (no such package):
    required by: world[unzip]
Removing intermediate container 0f3e982fcf5a

**Comment by AlexxIT** [comment]
Fixed in 0.2.0
