### ISSUE TITLE
Instalation crashes in RPi3 RaspiOS, Docker, HA supervised

### ISSUE THREAD

**Issue by FilipCZE** [AlexxIT/hassio-addons#12]
Hello! Im trying to install this addon at RPi3B running RaspiOS and Docker with HA supervised... The installation crashes every time Im trying to instal... What can be the issue? What am I supposed to do?

**Comment by AlexxIT** [comment]
The installation of what goes down?

**Comment by FilipCZE** [comment]
![image](https://user-images.githubusercontent.com/64529754/112722535-6876e780-8f0a-11eb-9e33-1053f3f55ffb.png)
![image](https://user-images.githubusercontent.com/64529754/112722543-7af12100-8f0a-11eb-9f5a-ec25994258c9.png)
When I push do install button it is somehow installing but after while, there is not installed addon. I can just push the install button nothing more.... What am I supposed to do?

**Comment by FilipCZE** [comment]
Do I need to install something more on RaspiOS by SSH?

**Comment by 1boko1** [comment]
Hello,

I have the same issue. 
There is my log :

21-03-30 14:45:49 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build a889bffc/armv7-addon-rtsp2webrtc:0.1.4: The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2
21-03-30 14:45:49 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM
Step 2/15 : FROM $BUILD_FROM
 ---> c04f52c3c7ff
Step 3/15 : RUN apk add --no-cache unzip go jq
 ---> Running in 21e752f47345
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  go (no such package):
    required by: world[go]
  unzip (no such package):
    required by: world[unzip]
Removing intermediate container 21e752f47345

**Comment by AlexxIT** [comment]
Duplicate #10

**Comment by AlexxIT** [comment]
Fixed in 0.2.0
