### ISSUE TITLE
noise instead of a picture

### ISSUE THREAD

**Issue by eugene-ki** [AlexxIT/hassio-addons#13]
I have a Reolink E1 Pro. It's notice as compatible. But there is noise instead of a picture. It's working after restart the camera for some time and get fault quick. With VLC I always have correct stream. What the problem it can be?
![2021-04-11_11-25-46](https://user-images.githubusercontent.com/24496958/114297498-abfc5480-9ab9-11eb-8e6b-ff54051f3f75.png)

**Comment by AlexxIT** [comment]
Maybe problem with data and browser can't decode it
Check this version and also read FAQ
https://github.com/AlexxIT/WebRTC
