### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by DendelX** [AlexxIT/hassio-addons#14]
Hi, 

Since I use the addon, I'm observed a masive  and increasing cpu using. It starts at one determined time each morning and keeps rising until I restart home assistant. Then all be fine until next day. 

Here you can see rtsp2webrtc_v4_ cpu use just before restart. 

![high cpu](https://user-images.githubusercontent.com/51743530/118634396-c4efd800-b7d2-11eb-90ac-a87c8e2b96a0.jpg)

Do you have any idea about this?

**Comment by way2many** [comment]
Unfortunately, same here. Not sure what is causing it.

**Comment by AlexxIT** [comment]
This is wrong repo for this issue
