### ISSUE TITLE
Error Running Container

### ISSUE THREAD

**Issue by brokerandyT2** [AlexxIT/hassio-addons#17]
Container starts but logs throw an error about the port being taken.  It would be great to either be able to configure the port, or have the docker file to cause the container to run on a different port (To be fair, I can't find the conflict :| )

Logs:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
{
  "server": {
    "http_port": ":8083"
  },
  "streams": {
    "Sonoff": {
      "url": "rtsp://xxxxx:xxxxxx@IPAddress/live"
    }
  }
}
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
2022/01/20 14:17:37 Stream Try Connect Sonoff
[GIN-debug] Loaded HTML Templates (2): 
	- 
	- index.tmpl
[GIN-debug] GET    /                         --> main.serveHTTP.func1 (3 handlers)
[GIN-debug] POST   /recive                   --> main.HTTPAPIServerStreamWebRTC (3 handlers)
[GIN-debug] GET    /codec/:uuid              --> main.serveHTTP.func2 (3 handlers)
[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
2022/01/20 14:17:37 Server Start Awaiting Signal
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8083
[GIN-debug] [ERROR] listen tcp :8083: bind: address already in use
2022/01/20 14:17:37 Start HTTP Server error listen tcp :8083: bind: address already in use

**Comment by AlexxIT** [comment]
This addon is no longer supported. Use the integration:
https://github.com/AlexxIT/WebRTC
