### ISSUE TITLE
Intermittent fails to play

### ISSUE THREAD

**Issue by tunerooster** [AlexxIT/hassio-addons#18]
First, I have been highly impressed and satisfied with this plugin.  Before this, all options were totally inadequate.  Thank you for this!

I have, however, encountered an intermittent failure where the video fails to play (says: no video).  In trying to troubleshoot this I encountered the following:

- Running `netstat -l` displayed over 900 of the following lines:
`udp        0      0 0.0.0.0:5353            0.0.0.0:*`
- Running `lsof -p <pid of rtsp2webrtc>` similarly displayed > 900 lines of this:
`rtsp2webr 14132 root  174u     IPv4 94851035      0t0      UDP *:mdns`

After killing rtsp2webrtc (it restarts automatically), `netstat` shows only 4 listeners and `lsof` shows only 2 open fd's.

I don't have any additional data at present, but I can run any additional diagnostics you would like, when it re-occurs.

Please advise...

P.S.  I am running HA 2021.12.8
         I couldn't find how to display the rtps2webrtv version, but a `ps` shows `rtsp2webrtc_v5_amd64`

**Comment by tunerooster** [comment]
It has happened again...  Almost 500 repeating lines of:
```
rtsp2webr 22578 root  410u     IPv4 142154278      0t0       UDP *:mdns 
rtsp2webr 22578 root  411u     IPv4 142158064      0t0       UDP *:mdns 
rtsp2webr 22578 root  412u     IPv4 142156263      0t0       UDP *:mdns 
rtsp2webr 22578 root  413u     IPv4 142158911      0t0       UDP *:mdns 
rtsp2webr 22578 root  414u     IPv4 142159415      0t0       UDP *:mdns 
rtsp2webr 22578 root  415u     IPv4 142158525      0t0       UDP *:mdns 
rtsp2webr 22578 root  416u     IPv4 142160927      0t0       UDP *:mdns 
...
```
Please advise.

**Comment by AlexxIT** [comment]
This addon is no longer supported. Use the integration:
https://github.com/AlexxIT/WebRTC

**Comment by tunerooster** [comment]
I am using the WebRTC HACS integration.  I must just be posting on the wrong github page.   I will repost in the correct place.

Thanks for directing me...

**Comment by AlexxIT** [comment]
No video is a keyframe problem. WebRTC starts the stream after receiving the first keyframe within 10 seconds.  Otherwise the connection to the camera is dropped.

**Comment by tunerooster** [comment]
I'm not familiar technically to understand what you are saying.  Are you saying this is not a WebRTC issue?

With no other solution, I would be tempted to write a script to count the occurrences of open fd's from ```lsof -p``` and if there are  are to many, to kill the webrtc process and let it restart.

Doing this manually seems to work to force start the video in HA panels which are showing "no video", but it seems like a klugy thing to do.  I was hoping there would be a fix to correct the underlying problem.

Please advise further...

Thanks!

**Comment by AlexxIT** [comment]
This is your camera settings issue
