### ISSUE TITLE
SSHTunnel failed to start with error s6-overlay-suexec: fatal: can only run as pid 1 

### ISSUE THREAD

**Issue by 2Frez** [AlexxIT/hassio-addons#19]
Installed and configured your addon on Home Assistant OS 8.1 (Home Assistant Core 2022.5.5)
After run get in addon's log only one line:
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by AlexxIT** [comment]
What device do you using for Hass server?

**Comment by emerkushev** [comment]
Same issue

HA version(haos): 2022.8.7
Device: Raspberry Pi 4

**Comment by 2Frez** [comment]
> What device do you using for Hass server?

Raspberry Pi 3B

**Comment by AlexxIT** [comment]
Should be fixed in latest release
