### ISSUE TITLE
Can't install the addon

### ISSUE THREAD

**Issue by hillout** [AlexxIT/hassio-addons#4]
Hi, 

Trying to install thew new version, once I click on the install button in the Superviser page it returns back with an error: 

<img width="610" alt="Снимок экрана 2021-01-13 в 10 13 25" src="https://user-images.githubusercontent.com/15137897/104418635-449d3a00-5588-11eb-933d-84a988b6c039.png">

Logs showing this: 

21-01-13 07:09:38 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build a889bffc/armv7-addon-rtsp2webrtc:0.1.4: The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2
21-01-13 07:09:38 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM
Step 2/15 : FROM $BUILD_FROM
 ---> ad4dcc921139
Step 3/15 : RUN apk add --no-cache unzip go jq
 ---> Running in f6110c83e54e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armv7/APKINDEX.tar.gz: temporary error (try again later)

**Comment by AlexxIT** [comment]
`temporary error (try again later)` - it is in your logs. Some problems with Internet I think

**Comment by hillout** [comment]
No, Internet is fine, I can ping any page by it's domain. Wget has fetched the file depicted in the log. Any suggestions? 
Не, Интернет работает стабильно, внешние ресурсы резолвятся и пингуются. Wget c терминала файл забирает.

**Comment by AlexxIT** [comment]
I plan in future versions build containers by myself. For now I don't know other solutions that problem

**Comment by aatumaykin** [comment]
Столкнулся с такой же проблемой

**Comment by aatumaykin** [comment]
21-01-31 15:33:01 INFO (SyncWorker_3) [supervisor.docker.addon] Starting build for a889bffc/armv7-addon-rtsp2webrtc:0.1.4
21-01-31 15:33:06 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build a889bffc/armv7-addon-rtsp2webrtc:0.1.4: The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2
21-01-31 15:33:06 ERROR (SyncWorker_3) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM
Step 2/15 : FROM $BUILD_FROM
 ---> 499528b366b0
Step 3/15 : RUN apk add --no-cache unzip go jq
 ---> Running in 2f54f7764dbd
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  go (no such package):
    required by: world[go]
  unzip (no such package):
    required by: world[unzip]
Removing intermediate container 2f54f7764dbd

**Comment by 1300371** [comment]
Same here ... 
Hope it will be fixed 👍 
```
21-02-09 21:28:53 INFO (SyncWorker_3) [supervisor.docker.addon] Starting build for a889bffc/armv7-addon-rtsp2webrtc:0.1.4
21-02-09 21:28:58 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build a889bffc/armv7-addon-rtsp2webrtc:0.1.4: The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2
21-02-09 21:28:58 ERROR (SyncWorker_3) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM
Step 2/15 : FROM $BUILD_FROM
 ---> 21461176cb52
Step 3/15 : RUN apk add --no-cache unzip go jq
 ---> Running in fd28e6614c8a
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  go (no such package):
    required by: world[go]
  unzip (no such package):
    required by: world[unzip]
Removing intermediate container fd28e6614c8a
```
