### ISSUE TITLE
HA snapshot size

### ISSUE THREAD

**Issue by razvanmdobre** [AlexxIT/hassio-addons#6]
After installing the RTSP2WebRTC add-on, the size of the full snapshot increased by ~150MB !!!
![image](https://user-images.githubusercontent.com/19249854/106119038-69cfa200-615d-11eb-89e4-5595832429f8.png)

**Comment by razvanmdobre** [comment]
any news about this issue?

**Comment by AlexxIT** [comment]
It can be fixed. But I should create public docker container. Never done it before and don't have time in near future.

**Comment by AlexxIT** [comment]
Fixed in 0.2.0
