### ISSUE TITLE
Failed to install addon

### ISSUE THREAD

**Issue by BDvirus** [AlexxIT/hassio-addons#7]
The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2

Logs:

21-01-30 19:31:01 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for 1d3934f5/armv7-addon-rtsp2webrtc:0.1.4
21-01-30 19:31:09 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build 1d3934f5/armv7-addon-rtsp2webrtc:0.1.4: The command '/bin/ash -o pipefail -c apk add --no-cache unzip go jq' returned a non-zero code: 2
21-01-30 19:31:09 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM
Step 2/15 : FROM $BUILD_FROM
 ---> 499528b366b0
Step 3/15 : RUN apk add --no-cache unzip go jq
 ---> Running in 1125292e7677
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
ERROR: unable to select packages:

  go (no such package):
    required by: world[go]
  unzip (no such package):
    required by: world[unzip]
Removing intermediate container 1125292e7677

Version | 2021.1.5
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.83-v7+
CPU Architecture | armv7l

**Comment by AlexxIT** [comment]
Duplicate #4
