### ISSUE TITLE
FR: expand RTSP2WebRTC webpage to show multiple streams

### ISSUE THREAD

**Issue by HIT2022** [AlexxIT/hassio-addons#8]
Thanks for getting this add-on out. In lieu of a JS wizard coming along and hooking us up with a lovelace card, having more than 1 stream shown on the UI at a time would up the use case for sticking with just the UI. Many folks use cameras in HA for tablet views, so quick and dirty at-a-glance overview of all feeds at once is usually ideal.

**Comment by johanudden** [comment]
👍

**Comment by AlexxIT** [comment]
No longer relevant.
